---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-external
  namespace: nginx-ingress-external
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: nginx-ingress-external
      interval: 5m
  values:
    replicaCount: 1
    controller:
      kind: DaemonSet
      allowSnippetAnnotations: true
      containerPort:
        http: 80
        https: 443
        ssh: 22
      networkPolicy:
        enabled: false
      admissionWebhooks:
        certManager:
          enabled: false
      extraArgs:
        default-ssl-certificate: nginx-ingress-external/login-no-cert
      service:
        externalTrafficPolicy: "Local"
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-name: "nginx-ingress-infra-external-lb"
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"

          # Health checks
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"

          # Fix for internal traffic with authentik
          service.beta.kubernetes.io/do-loadbalancer-hostname: infra-ext-lb.login.no
          external-dns.alpha.kubernetes.io/hostname: "infra-ext-lb.login.no"

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
    
      ingressClassResource:
        name: nginx-external
        enabled: true
        default: false
        controllerValue: k8s.io/external-ingress-nginx
    tcp:
      "22": gitlab/gitlab-prod-gitlab-shell:22:PROXY
