---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-restore-psql-v2
  namespace: authentik
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  monitoring:
    enablePodMonitor: true
  description: Postgres for Authentik
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  postgresql:
    parameters:
      timezone: "Europe/Oslo"
  superuserSecret:
    name: authentik-db-credentials

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://login-infra-prod-psql-backups/authentik
      s3Credentials:
        accessKeyId:
          name: authentik-pg-backup
          key: access
        secretAccessKey:
          name: authentik-pg-backup
          key: secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-restore-psql-v2-backup
  namespace: authentik
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: authentik-restore-psql-v2
