apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zammad-revocery-psql-backup
  namespace: zammad
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: zammad-recovery
